"""citizens

Revision ID: 202207210104
Revises: 202204021731
Create Date: 2022-07-21 01:04:22.956756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202207210104'
down_revision = '202204021731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sb_citizen_statuses',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['sb_users.id'], name=op.f('fk_sb_citizen_statuses_created_by_id_sb_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['sb_users.id'], name=op.f('fk_sb_citizen_statuses_updated_by_id_sb_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sb_citizen_statuses'))
    )
    op.create_table('sb_citizens',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_account_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('age', sa.BigInteger(), nullable=True),
    sa.Column('salary', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['sb_client_accounts.id'], name=op.f('fk_sb_citizens_client_account_id_sb_client_accounts')),
    sa.ForeignKeyConstraint(['created_by_id'], ['sb_users.id'], name=op.f('fk_sb_citizens_created_by_id_sb_users')),
    sa.ForeignKeyConstraint(['status_id'], ['sb_citizen_statuses.id'], name=op.f('fk_sb_citizens_status_id_sb_citizen_statuses')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['sb_users.id'], name=op.f('fk_sb_citizens_updated_by_id_sb_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sb_citizens'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sb_citizens')
    op.drop_table('sb_citizen_statuses')
    # ### end Alembic commands ###
