"""bosses relation

Revision ID: 202207212043
Revises: 202207210105
Create Date: 2022-07-21 20:43:01.695391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202207212043'
down_revision = '202207210104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sb_citizens', sa.Column('boss_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_sb_citizens_boss_id_sb_citizens'), 'sb_citizens', 'sb_citizens', ['boss_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sb_citizens_boss_id_sb_citizens'), 'sb_citizens', type_='foreignkey')
    op.drop_column('sb_citizens', 'boss_id')
    # ### end Alembic commands ###
