"""test data

Revision ID: 202207212045
Revises: 202207212043
Create Date: 2022-07-21 00:47:44.492102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '202207212045'
down_revision = '202207212043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO sb_users(password_hash, first_name, last_name, email, email_verified, created_at, created_by_id) VALUES ('pbkdf2:sha256:150000$oHDbyhxl$e0ee6c34bfc4626c9f8680ae91f021de7c5446674e0d79e61122b49d71e98d39', 'Almaz', 'Khamidullin', 'almaz1c@yandex.ru', TRUE, '2022-04-02 17:59:00', 1)")
    op.execute("INSERT INTO sb_roles(name, created_at, created_by_id) VALUES ('SA', '2022-04-02 18:05:00', 1)")
    op.execute("INSERT INTO sb_roles(name, created_at, created_by_id) VALUES ('AA', '2022-04-02 18:05:00', 1)")
    op.execute("INSERT INTO sb_roles(name, created_at, created_by_id) VALUES ('CA', '2022-04-02 18:05:00', 1)")
    op.execute("INSERT INTO sb_roles(name, created_at, created_by_id) VALUES ('BK', '2022-04-02 18:05:00', 1)")
    op.execute("INSERT INTO sb_roles(name, created_at, created_by_id) VALUES ('EM', '2022-04-02 18:05:00', 1)")

    # Client test company - Bur 1
    op.execute("INSERT INTO sb_organizations(name, address, city, country, postal, created_by_id, organization_number, created_at) VALUES('Paris', 'Central street 1', 'Paris', 'RU', '420012', 1, '9214534663', '2022-04-02 17:59:00')")
    op.execute("INSERT INTO sb_client_accounts(display_name, active, accounting_currency, organization_id, upload_email, created_by_id, unique_name, sequence_number, organization_number, created_at) VALUES ('Paris', true, 'RUB', 1, NULL, 1, 'Paris', 1, '9214534663', '2022-04-02 17:59:00' )")

    # Client test company - Bur 2
    op.execute("INSERT INTO sb_organizations(name, address, city, country, postal, created_by_id, organization_number, created_at) VALUES('London', 'Central street 2', 'London', 'RU', '420013', 1, '9214534664', '2022-04-02 17:59:00')")
    op.execute("INSERT INTO sb_client_accounts(display_name, active, accounting_currency, organization_id, upload_email, created_by_id, unique_name, sequence_number, organization_number, created_at) VALUES ('London', true, 'RUB', 1, NULL, 1, 'London', 1, '9214534664', '2022-04-02 17:59:00' )")

    # Service test company - Office
    op.execute("INSERT INTO sb_organizations(name, address, city, country, postal, created_by_id, organization_number, created_at) VALUES('Alabuga', 'Central street 3', 'Alabuga', 'RU', '420014', 1, '9214534665', '2022-04-02 17:59:00')")
    op.execute("INSERT INTO sb_client_accounts(display_name, active, accounting_currency, organization_id, upload_email, created_by_id, unique_name, sequence_number, organization_number, created_at) VALUES ('Alabuga', true, 'RUB', 1, NULL, 1, 'Alabuga', 1, '9214534665', '2022-04-02 17:59:00' )")

    # User 1 works in Office
    op.execute("INSERT INTO sb_client_account_users(created_at, user_id, role_id, created_by_id, client_account_id, is_active) VALUES('2022-04-02 18:05:00', 1, 2, 1, 3, TRUE)")

    # Service company (Office) services client companies (Bur 1 and bur 2)
    op.execute("INSERT INTO sb_contracts(created_at, accounting_client_account_id, client_account_id, created_by_id) VALUES('2022-04-02 18:05:00', 3, 1, 1)")
    op.execute("INSERT INTO sb_contracts(created_at, accounting_client_account_id, client_account_id, created_by_id) VALUES('2022-04-02 18:05:00', 3, 2, 1)")



    op.execute("INSERT INTO sb_citizen_statuses(id, name, created_at, created_by_id) VALUES (1, 'Graf', '2022-04-02 22:22:00', 1)")
    op.execute("INSERT INTO sb_citizen_statuses(id, name, created_at, created_by_id) VALUES (2, 'Worker', '2022-04-02 22:22:00', 1)")
    op.execute("INSERT INTO sb_citizen_statuses(id, name, created_at, created_by_id) VALUES (3, 'King', '2022-04-02 22:22:00', 1)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id) VALUES ('John', 'Johnson', '2022-04-02 22:22:00', 1, 2, 35, 200000, 3)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Bill', 'Klinton', '2022-04-02 22:22:00', 1, 2, 42, 450000, 1, 1)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Aaron', 'Vuh', '2022-04-02 22:22:00', 1, 2, 42, 45000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Amy', 'Sthone', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Viva', 'Karson', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Andy', 'Micle', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Tony', 'Montano', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Tony', 'Robinson', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('James', 'James', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Bill', 'Tornrton', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Lisa', 'Dawson', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Sandy', 'Micle', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Stron', 'Kelly', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Bill', 'Viasdes', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Jeph', 'Vasces', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Jane', 'Air', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('John', 'Golt', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Sea', 'Mea', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Vie', 'Torston', '2022-04-02 22:22:00', 1, 2, 42, 450000, 2, 2)")

    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id) VALUES ('Jack', 'Jackson', '2022-04-02 22:22:00', 1, 1, 35, 200000, 3)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Klin', 'Blinken', '2022-04-02 22:22:00', 1, 1, 42, 450000, 1, 20)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Aaron', 'Vuh', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 21)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Amy', 'Sthone', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Veriva', 'Karson', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Afgndy', 'Micle', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Tofghny', 'Montano', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Todseny', 'Robinson', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Jamewes', 'James', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Bigdll', 'Tornrton', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Libvcsa', 'Dawson', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Sawndy', 'Micle', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Strwdon', 'Kelly', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Bilbl', 'Viasdes', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Jexeph', 'Vasces', '2022-04-02 22:22:00', 1, 1, 42, 27000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Jassne', 'Air', '2022-04-02 22:22:00', 1, 1, 42, 26000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Jodfhn', 'Golt', '2022-04-02 22:22:00', 1, 1, 42, 26000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Seera', 'Mea', '2022-04-02 22:22:00', 1, 1, 42, 26000, 2, 22)")
    op.execute("INSERT INTO sb_citizens(name, surname, created_at, created_by_id, client_account_id, age, salary, status_id, boss_id) VALUES ('Virewe', 'Torston', '2022-04-02 22:22:00', 1, 1, 42, 26000, 2, 22)")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.execute('DELETE FROM sb_temperature_sensor_measurements')
    op.execute('DELETE FROM sb_citizens')
    op.execute('DELETE FROM sb_citizen_statuses')
    op.execute('DELETE FROM sb_contracts WHERE id in (1, 2)')
    op.execute('DELETE FROM sb_client_account_users WHERE id in (1)')
    op.execute('DELETE FROM sb_client_accounts WHERE id in (1, 2, 3)')
    op.execute('DELETE FROM sb_organizations WHERE id in (1,2, 3)')
    op.execute('DELETE FROM sb_roles WHERE id in (1,2,3,4,5)')
    op.execute('DELETE FROM sb_users WHERE id in (1)')
    # ### end Alembic commands ###
